"""
LangChain Expression Language (LCEL) Chain Definitions

This module defines various chains for the Virtual TA system using LCEL.
Each chain is specialized for different types of queries and responses.

Created: 2/21/2024
Updated: Current Date
"""

from langchain_core.prompts import PromptTemplate, ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser, PydanticOutputParser, JsonOutputParser
from langchain_core.runnables import RunnableParallel, RunnablePassthrough
from typing import Dict, Any, Optional, Union, List
from pydantic import BaseModel, Field, validator
from langchain.schema.language_model import BaseLanguageModel
import logging

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Output Parsers
output_parser = StrOutputParser()
json_parser = JsonOutputParser()

class Label(BaseModel):
    """Pydantic model for router output."""
    query: str = Field(description="The new query generated by the router")
    label: str = Field(description="The classification label for the query")
    
    @validator('label')
    def validate_label(cls, v):
        """Validate that the label is one of the allowed values."""
        allowed_labels = [
            'analytics', 'explain-python', 'explain-sql', 
            'exercise-python', 'exercise-sql', 'course',
            'debug', 'chat'
        ]
        if v not in allowed_labels:
            raise ValueError(f'Label must be one of {allowed_labels}')
        return v

pydantic_parser = PydanticOutputParser(pydantic_object=Label)

def _create_chain(
    template: str,
    output_parser: Any,
    llm: Optional[BaseLanguageModel] = None,
    max_retries: int = 2
) -> Any:
    """
    Create a generic chain with error handling and retries.
    
    Args:
        template: The prompt template string
        output_parser: Parser for the LLM output
        llm: Language model to use
        max_retries: Maximum number of retry attempts
        
    Returns:
        A runnable chain
    """
    try:
        prompt = ChatPromptTemplate.from_template(template)
        setup = RunnableParallel(
            {key: RunnablePassthrough() for key in prompt.input_variables}
        )
        
        # Add retry logic
        def execute_with_retry(inputs: Dict[str, Any]) -> Any:
            for attempt in range(max_retries + 1):
                try:
                    return (setup | prompt | llm | output_parser).invoke(inputs)
                except Exception as e:
                    if attempt == max_retries:
                        logger.error(f"Chain execution failed after {max_retries} retries: {str(e)}")
                        raise
                    logger.warning(f"Attempt {attempt + 1} failed, retrying...")
            
        return execute_with_retry
        
    except Exception as e:
        logger.error(f"Error creating chain: {str(e)}")
        raise


# Chain Templates
EXAM_TEMPLATE = """
You are a Socratic virtual TA for an undergraduate data analytics course in Goizueta Business School. 
Your task is to guide students through their midterm exam queries using a Socratic approach.

Before generating a response, analyze the query systematically:
1. Understand the query from a beginner Python data analytics perspective
2. Break down the problem into logical steps
3. Identify the key concepts being tested
4. Determine the most appropriate hint or question to guide the student

Your response should:
1. Ask a thought-provoking question that leads the student to the next step
2. Highlight relevant course concepts without giving away the answer
3. Encourage problem-solving and analytical thinking
4. Use clear, beginner-friendly language
5. Stay within 300 tokens
6. Format output for readability using markdown

Query: <query>{query}</query>

Remember: Guide don't solve. Help students discover the answer through critical thinking.

Your response:
"""

ROUTER_TEMPLATE = """
You are an expert query classifier for a virtual teaching assistant system.
Your task is to analyze and classify the current query into the most appropriate category.

Current Query: <query>{query}</query>
Previous Context:
- Previous Query: {previous_query}
- Previous Classification: {previous_classification}

Classification Process:
1. Analyze the query and its context
2. Identify the primary topic and intent
3. Classify according to these categories:
   - analytics: Data analysis with pandas/sklearn (manipulation, visualization, statistics)
   - explain-python: Python programming concepts and syntax
   - explain-sql: SQL/MySQL concepts and syntax
   - exercise-python: Python programming practice questions
   - exercise-sql: SQL/MySQL practice questions
   - course: Course-specific information (syllabus, assignments)
   - debug: Code errors and debugging help
   - chat: General conversation or unclassified queries

Output a JSON object with:
1. "query": Enhanced version of the query for better processing
2. "label": One of the classification categories listed above

Response Format:
{{
    "query": "enhanced query text",
    "label": "category"
}}
"""

def exam_chain(llm: BaseLanguageModel) -> Any:
    """
    Create a chain for handling exam-related queries using a Socratic approach.
    
    Args:
        llm: The language model to use
        
    Returns:
        A runnable chain for exam guidance
    """
    return _create_chain(EXAM_TEMPLATE, output_parser, llm)

def router_chain(llm: BaseLanguageModel) -> Any:
    """
    Create a chain for classifying user queries into appropriate categories.
    
    Args:
        llm: The language model to use
        
    Returns:
        A runnable chain that outputs a Label object with query and classification
    """
    try:
        # Use ChatPromptTemplate instead of PromptTemplate for better handling
        router_prompt = ChatPromptTemplate.from_template(ROUTER_TEMPLATE)
        setup = RunnableParallel(
            {"query": RunnablePassthrough(),
             "previous_query": RunnablePassthrough(),
             "previous_classification": RunnablePassthrough()}
        )
        
        chain = setup | router_prompt | llm | pydantic_parser
        logger.info("Router chain created successfully")
        return chain
        
    except Exception as e:
        logger.error(f"Error creating router chain: {str(e)}")
        raise

# Exercise Chain Template
EXERCISE_TEMPLATE = """
You are an expert at creating Python and SQL exercise questions for business students.
Your task is to generate engaging, contextual multiple-choice questions.

Analysis Steps:
1. Topic Analysis:
   - Current Query: {current_query}
   - Previous Query: {previous_query}
   - Identify main concept and subtopics
   - Consider student's skill level: {skill_level}

2. Question Design:
   - Create a business-relevant scenario
   - Incorporate real-world applications
   - Ensure appropriate difficulty
   - Avoid repetition with previous exercise: {previous_exercise}

Response Format:
1. Brief Concept Overview (2-3 sentences)
2. Business Scenario
3. Code Snippet (using markdown):
   ```python
   # Your code here (max 5 lines)
   ```
4. Question Statement
5. Multiple Choice Options (A-D)
6. Correct Answer with Explanation

Guidelines:
- Use clear, beginner-friendly language
- Focus on practical applications
- Include helpful comments in code
- Limit to 250 tokens
- Format for readability using markdown
"""

def exercise_chain(llm: BaseLanguageModel) -> Any:
    """
    Create a chain for generating exercise questions with proper context and progression.
    
    Args:
        llm: The language model to use
        
    Returns:
        A runnable chain for generating exercise questions
        
    Example:
        chain = exercise_chain(llm)
        response = chain.stream(input={
            'current_query': 'Create a pandas exercise',
            'previous_query': 'Previous question about filtering',
            'skill_level': 'beginner',
            'previous_exercise': 'Last exercise about groupby'
        })
    """
    try:
        prompt = ChatPromptTemplate.from_template(EXERCISE_TEMPLATE)
        setup = RunnableParallel(
            {"current_query": RunnablePassthrough(),
             "previous_query": RunnablePassthrough(),
             "skill_level": RunnablePassthrough(),
             "previous_exercise": RunnablePassthrough()}
        )
        
        chain = setup | prompt | llm | output_parser
        logger.info("Exercise chain created successfully")
        return chain
        
    except Exception as e:
        logger.error(f"Error creating exercise chain: {str(e)}")
        raise

# Explain Chain Template
EXPLAIN_TEMPLATE = """
You are an expert at explaining technical concepts to business students.
Your focus areas are Python programming, SQL, and data analytics.

Query: <query>{query}</query>
Previous Context: <history>{chat_history}</history>

Response Structure:
1. Concept Overview:
   - Clear, concise explanation
   - Business relevance
   - Key points and common use cases

2. Code Example:
   ```python
   # Your code here (max 5 lines)
   # Include helpful comments
   ```

3. Business Application:
   - Real-world scenario
   - Practical benefits
   - Common use cases

4. Key Takeaways:
   - Main points to remember
   - Best practices
   - Common pitfalls to avoid

Guidelines:
- Use business-friendly language
- Focus on practical applications
- Include relevant examples
- Format using markdown
- Limit to 250 tokens
"""

def explain_chain(llm: BaseLanguageModel) -> Any:
    """
    Create a chain for explaining technical concepts with business context.
    
    Args:
        llm: The language model to use
        
    Returns:
        A runnable chain for generating explanations
        
    Example:
        chain = explain_chain(llm)
        response = chain.stream(input={
            'query': 'Explain pandas groupby',
            'chat_history': 'Previous discussion about data analysis'
        })
    """
    try:
        prompt = ChatPromptTemplate.from_template(EXPLAIN_TEMPLATE)
        setup = RunnableParallel(
            {"query": RunnablePassthrough(),
             "chat_history": RunnablePassthrough()}
        )
        
        chain = setup | prompt | llm | output_parser
        logger.info("Explain chain created successfully")
        return chain
        
    except Exception as e:
        logger.error(f"Error creating explain chain: {str(e)}")
        raise

# Debug Chain Template
DEBUG_TEMPLATE = """
You are an expert at helping students debug Python and SQL code.
Your role is to guide them through the debugging process without solving it for them.

Error Context:
Query: <query>{query}</query>
History: <history>{chat_history}</history>

Analysis Steps:
1. Error Understanding:
   - Identify error type and location
   - Common causes for this error
   - Relevant context from code

2. Debugging Strategy:
   - Systematic approach to finding the issue
   - Key areas to check
   - Common pitfalls to avoid

3. Guided Resolution:
   - Questions to consider
   - Steps to investigate
   - Verification methods

Guidelines:
- Guide don't solve
- Use encouraging language
- Focus on learning opportunities
- Suggest debugging techniques
- Limit to 250 tokens
- Format using markdown
"""

def debug_chain(llm: BaseLanguageModel) -> Any:
    """
    Create a chain for guiding students through debugging process.
    
    Args:
        llm: The language model to use
        
    Returns:
        A runnable chain for debugging guidance
        
    Example:
        chain = debug_chain(llm)
        response = chain.stream(input={
            'query': 'Getting IndexError in my code',
            'chat_history': 'Previous debugging attempts'
        })
    """
    try:
        prompt = ChatPromptTemplate.from_template(DEBUG_TEMPLATE)
        setup = RunnableParallel(
            {"query": RunnablePassthrough(),
             "chat_history": RunnablePassthrough()}
        )
        
        chain = setup | prompt | llm | output_parser
        logger.info("Debug chain created successfully")
        return chain
        
    except Exception as e:
        logger.error(f"Error creating debug chain: {str(e)}")
        raise

# RAG Chain Template
RAG_TEMPLATE = """
You are an expert at retrieving and explaining course-related information to students.
Your task is to provide accurate, context-aware responses based on course materials.

Input Information:
Query: {query}
Retrieved Context: {context}

Response Structure:
1. Direct Answer:
   - Clear, focused response to the query
   - Based on relevant context only
   - Highlight key information

2. Additional Context (if relevant):
   - Related course concepts
   - Important deadlines or requirements
   - Common misconceptions

3. Next Steps (optional):
   - Suggested readings
   - Related topics
   - Practice exercises

Guidelines:
- Use only relevant context
- Be clear and concise
- Format using markdown
- Limit to 250 tokens
- Focus on accuracy
"""

def rag_chain(llm: BaseLanguageModel, retriever: Any) -> Any:
    """
    Create a chain for retrieving and explaining course-related information.
    
    Args:
        llm: The language model to use
        retriever: Vector store retriever for course content
        
    Returns:
        A runnable chain for RAG-based responses
        
    Example:
        chain = rag_chain(llm, retriever)
        response = chain.stream(query='What is the course schedule?')
    """
    try:
        prompt = ChatPromptTemplate.from_template(RAG_TEMPLATE)
        setup_retrieval = RunnableParallel(
            {"context": retriever,
             "query": RunnablePassthrough()}
        )
        
        chain = setup_retrieval | prompt | llm | output_parser
        logger.info("RAG chain created successfully")
        return chain
        
    except Exception as e:
        logger.error(f"Error creating RAG chain: {str(e)}")
        raise

# Chat Chain Template
CHAT_TEMPLATE = """
You are a friendly virtual TA for an Applied Data Analytics course.
Your role is to engage with students in a helpful and encouraging manner.

Current Message: {query}
Chat History: {chat_history}

Response Guidelines:
1. Tone and Style:
   - Professional yet friendly
   - Encouraging and supportive
   - Clear and concise

2. Content Focus:
   - Stay relevant to data analytics
   - Connect to course concepts
   - Provide practical insights

3. Engagement:
   - Acknowledge student's question
   - Show understanding
   - Maintain educational focus

Format:
- Keep responses concise (100 tokens max)
- Use clear language
- Format using markdown when needed
"""

def chat_chain(llm: BaseLanguageModel) -> Any:
    """
    Create a chain for general conversation with students.
    
    Args:
        llm: The language model to use
        
    Returns:
        A runnable chain for chat interactions
        
    Example:
        chain = chat_chain(llm)
        response = chain.stream(input={
            'query': 'How can I improve my Python skills?',
            'chat_history': 'Previous conversation about coding'
        })
    """
    try:
        prompt = ChatPromptTemplate.from_template(CHAT_TEMPLATE)
        setup = RunnableParallel(
            {"query": RunnablePassthrough(),
             "chat_history": RunnablePassthrough()}
        )
        
        chain = setup | prompt | llm | output_parser
        logger.info("Chat chain created successfully")
        return chain
        
    except Exception as e:
        logger.error(f"Error creating chat chain: {str(e)}")
        raise

# Analytics Chain Template
ANALYTICS_TEMPLATE = """
You are an expert at explaining data analytics concepts to business students.
Your focus is on practical applications using pandas, matplotlib, seaborn, and statsmodels.

Current Query: {query}
Previous Context: {chat_history}

Response Structure:
1. Concept Introduction:
   - Brief explanation
   - Business relevance
   - Common applications

2. Code Demonstration:
   ```python
   # Clear, commented code example (max 5 lines)
   # Focus on pandas, matplotlib, seaborn
   # Avoid scikit-learn unless specifically asked
   ```

3. Code Explanation:
   - Line-by-line breakdown
   - Key concepts highlighted
   - Common pitfalls to avoid

4. Business Context:
   - Real-world applications
   - Industry examples
   - Practical benefits

5. Further Learning:
   - Related concepts
   - Additional methods
   - Best practices

Guidelines:
- Use business-friendly language
- Focus on practical applications
- Include helpful comments
- Format using markdown
- Limit to 250 tokens
"""

def analytics_chain(llm: BaseLanguageModel) -> Any:
    """
    Create a chain for explaining data analytics concepts with business context.
    
    Args:
        llm: The language model to use
        
    Returns:
        A runnable chain for analytics explanations
        
    Example:
        chain = analytics_chain(llm)
        response = chain.stream(input={
            'query': 'How to create a line plot?',
            'chat_history': 'Previous discussion about visualization'
        })
    """
    try:
        prompt = ChatPromptTemplate.from_template(ANALYTICS_TEMPLATE)
        setup = RunnableParallel(
            {"query": RunnablePassthrough(),
             "chat_history": RunnablePassthrough()}
        )
        
        chain = setup | prompt | llm | output_parser
        logger.info("Analytics chain created successfully")
        return chain
        
    except Exception as e:
        logger.error(f"Error creating analytics chain: {str(e)}")
        raise
